### ISSUE TITLE
Combine cerebral-module and cerebral-provider

### ISSUE THREAD

**Issue by tomohiroarakawa** [OADA/cerebral-module#3]
I propose to combine `cerebral-module` and `cerebral-provider` into a single repository. Is there a use case where one is used and the other is not? If not, I think it is easier to maintain just one repository than maintaining two, especially given that `cerebral-provider` is currently a very small repository (containing just one source file).

**Comment by aultac** [comment]
Sounds like a great idea to me

**Comment by tomohiroarakawa** [comment]
`cerebral-provider` is now part of `cerebral-module`. See commit 0500bd4.

**Comment by tomohiroarakawa** [comment]
Released `cerebral-module` v4.0.0. Closing the issue.
